### ISSUE TITLE
Error when importing from __future__ in python 3.11

### ISSUE THREAD

**Issue by javiquinte** [GEOFON/fdsnws_scripts#13]
I had to manually fix another error:

```
Traceback (most recent call last):
  File "/home/schaeffj/.local/share/uv/tools/fdsnwsscripts/bin/fdsnws_fetch", line 5, in <module>
    from fdsnwsscripts.fdsnws_fetch import main
  File "/home/schaeffj/.local/share/uv/tools/fdsnwsscripts/lib/python3.11/site-packages/fdsnwsscripts/fdsnws_fetch.py", line 79
    from __future__ import (absolute_import, division, print_function,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
```

_Originally posted by @jschaeff in https://github.com/GEOFON/fdsnws_scripts/issues/11#issuecomment-2413354798_

**Comment by javiquinte** [comment]
Hi @jschaeff !
Could you please post what have you changed to make it work? Thanks in advance! 😃

**Comment by jschaeff** [comment]
Hi,

I moved the import line at the first position as suggested by the error message.
Weird that python treats this as an error...

Le 21 octobre 2024 14:15:39 GMT+02:00, Javier Quinteros ***@***.***> a écrit :

**Comment by petrrr** [comment]
@jschaeff I am not able to reproduce your observation. 

The import from __future__ follow a doc string, but it is the first import and the first effective command. So not sure there is any issue with the code.

**Comment by jschaeff** [comment]
I confirm that the problem is still there. Here is how I reproduce it:

1. Installation
    ```
    uv tool install fdsnwsscripts
    ```
2. launch
    ```
    fdsnws2sds -N FR -s 2023-01-01 -e 2023-12-31 -n 8 -m 1440 -Z -o waveforms --verbose
    Traceback (most recent call last):
    File "/home/schaeffj/.local/share/uv/tools/fdsnwsscripts/bin/fdsnws_fetch", line 5, in <module>
    from fdsnwsscripts.fdsnws_fetch import main
    File "/home/schaeffj/.local/share/uv/tools/fdsnwsscripts/lib/python3.11/site-packages/fdsnwsscripts/fdsnws_fetch.py", line 79
    from __future__ import (absolute_import, division, print_function,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    SyntaxError: from __future__ imports must occur at the beginning of the file error running fdsnws_fetch
    ```

Maybe it is due to the way the project is installed.

**Comment by petrrr** [comment]
@jschaeff: 
That is interesting. Installed with macports, which just uses setuptools. PyPI package & patch for 3.11 issue, but no modification to the __future__ import. 

I just tested with your with your call, just to be sure. 
No issue here ...

```
petr@kozel test-fdsnws-fetch % fdsnws2sds-3.11  -N FR -s 2023-01-01 -e 2023-12-31 -n 8 -m 1440 -Z -o waveforms --verbose
getting routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query?service=station&network=FR&starttime=2023-01-01&endtime=2023-12-31&format=post
getting data from https://ws.resif.fr/fdsnws/station/1/query
got 238085 bytes (text/plain) from https://ws.resif.fr/fdsnws/station/1/query

In case of problems with your request, plese use the contact form at

    http://www.orfeus-eu.org/organization/contact/form/?recipient=EIDA

getting routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query
getting data from https://ws.resif.fr/fdsnws/dataselect/1/query
request too large for https://ws.resif.fr/fdsnws/dataselect/1/query, splitting
getting data from https://ws.resif.fr/fdsnws/dataselect/1/query (0%..50%)
request too large for https://ws.resif.fr/fdsnws/dataselect/1/query, splitting
getting data from https://ws.resif.fr/fdsnws/dataselect/1/query (0%..25%)
request too large for https://ws.resif.fr/fdsnws/dataselect/1/query, splitting
getting data from https://ws.resif.fr/fdsnws/dataselect/1/query (0%..12%)
request too large for https://ws.resif.fr/fdsnws/dataselect/1/query, splitting
getting data from https://ws.resif.fr/fdsnws/dataselect/1/query (0%..6%)
```

**Comment by andres-h** [comment]
This was caused by double doc string. Fixed in 2025.275.
